# Generated by Django 4.1.1 on 2022-09-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulknotification',
            name='filter',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Success'), (3, 'Error')], default=1),
        ),
    ]
